export const defaultPatientData = {
  _id: null,
  patient_name: "",
  father_name: "",
  phone_number: "",
  age: null,
  gender: "",
  date_of_birth: null,
  address: "",
  city: "",
  check_nub: "",
  appointment_by: "",
  old_mrn: "",
  guardian: {
    relation: "",
    name: "",
    cnic: "",
    email: "",
    profession: "",
  },
  reference_history: {
    reference_by: "",
    history_type: "",
    public_notes: "",
  },
  createdAt: null,
  updatedAt: null,
  __v: 0,
};